import {
  normaliseLocatorData,
  renderExpression,
  renderPythonExpression,
} from './locator-expression';
import { ValidationFailedException } from '../../common/errors';
import type { LocatorData } from './ui-scanner.types';

/**
 * Locator rendering and validation (FR-UIS-010).
 *
 * These renderers are the TypeScript twin of
 * `engine/uiscanner/locator_generator.py`. The expected strings below are the
 * same ones that file's Python tests assert, which is what keeps a locator
 * edited in the browser identical to one generated by the engine.
 */
describe('locator expression rendering', () => {
  it('renders a role locator in both languages', () => {
    const data: LocatorData = {
      strategy: 'role',
      role: 'button',
      name: 'Login',
      exact: true,
    };
    expect(renderExpression(data)).toBe(
      "page.getByRole('button', { name: 'Login', exact: true })",
    );
    expect(renderPythonExpression(data)).toBe(
      'page.get_by_role("button", name="Login", exact=True)',
    );
  });

  it('renders a role locator with no name', () => {
    expect(renderExpression({ strategy: 'role', role: 'dialog' })).toBe(
      "page.getByRole('dialog')",
    );
  });

  it.each([
    ['label', "page.getByLabel('Email address', { exact: true })"],
    ['placeholder', "page.getByPlaceholder('Email address', { exact: true })"],
    ['text', "page.getByText('Email address', { exact: true })"],
  ])('renders a %s locator', (strategy, expected) => {
    expect(
      renderExpression({
        strategy: strategy as LocatorData['strategy'],
        value: 'Email address',
        exact: true,
      }),
    ).toBe(expected);
  });

  it('renders getByTestId only for the standard attribute', () => {
    expect(
      renderExpression({
        strategy: 'testId',
        value: 'login-submit',
        attribute: 'data-testid',
      }),
    ).toBe("page.getByTestId('login-submit')");
    expect(
      renderExpression({
        strategy: 'testId',
        value: 'login-submit',
        attribute: 'data-cy',
        selector: '[data-cy="login-submit"]',
      }),
    ).toBe('page.locator(\'[data-cy="login-submit"]\')');
  });

  it('renders a scoped locator as parent then child', () => {
    const data: LocatorData = {
      strategy: 'scopedRole',
      parent: { strategy: 'role', role: 'dialog', name: 'Edit user', exact: true },
      child: { strategy: 'role', role: 'button', name: 'Save', exact: true },
    };
    expect(renderExpression(data)).toBe(
      "page.getByRole('dialog', { name: 'Edit user', exact: true })" +
        ".getByRole('button', { name: 'Save', exact: true })",
    );
    expect(renderPythonExpression(data)).toBe(
      'page.get_by_role("dialog", name="Edit user", exact=True)' +
        '.get_by_role("button", name="Save", exact=True)',
    );
  });

  it('prefixes the frame chain', () => {
    const data: LocatorData = {
      strategy: 'role',
      role: 'button',
      name: 'Pay now',
      exact: true,
      frame: {
        path: ['iframe[title="Payment"]'],
        url: '',
        name: '',
        title: 'Payment',
        selector: 'iframe[title="Payment"]',
        parentIndex: 0,
        index: 1,
      },
    };
    expect(renderExpression(data)).toBe(
      'page.frameLocator(\'iframe[title="Payment"]\')' +
        ".getByRole('button', { name: 'Pay now', exact: true })",
    );
    expect(renderPythonExpression(data)).toBe(
      'page.frame_locator("iframe[title=\\"Payment\\"]")' +
        '.get_by_role("button", name="Pay now", exact=True)',
    );
  });

  it('escapes quotes in each language', () => {
    const data: LocatorData = { strategy: 'text', value: "It's here", exact: true };
    expect(renderExpression(data)).toBe(
      "page.getByText('It\\'s here', { exact: true })",
    );
    expect(renderPythonExpression(data)).toBe(
      'page.get_by_text("It\'s here", exact=True)',
    );
  });
});

describe('locator data validation', () => {
  it('accepts a well-formed role locator', () => {
    const data = normaliseLocatorData({
      strategy: 'role',
      role: 'button',
      name: 'Save',
      exact: true,
      junk: 'ignored',
    });
    expect(data.strategy).toBe('role');
    expect(data.role).toBe('button');
    expect(data).not.toHaveProperty('junk');
  });

  it('rejects an unknown strategy — nothing arbitrary ever becomes a locator', () => {
    expect(() => normaliseLocatorData({ strategy: 'eval', selector: 'x' })).toThrow(
      ValidationFailedException,
    );
  });

  it.each([
    [{ strategy: 'role' }, /needs a role/],
    [{ strategy: 'label' }, /needs a value/],
    [{ strategy: 'css' }, /needs a selector/],
    [{ strategy: 'xpath' }, /needs a selector/],
    [{ strategy: 'testId' }, /needs a value or a selector/],
    [{ strategy: 'scopedRole', parent: { strategy: 'role', role: 'dialog' } }, /parent and a child/],
  ])('rejects an incomplete locator (%p)', (input, message) => {
    expect(() => normaliseLocatorData(input as Record<string, unknown>)).toThrow(
      message,
    );
  });

  it('keeps a frame chain but bounds its depth', () => {
    const data = normaliseLocatorData({
      strategy: 'role',
      role: 'button',
      frame: { path: ['iframe#a', 'iframe#b'], index: 2 },
    });
    expect(data.frame?.path).toEqual(['iframe#a', 'iframe#b']);

    expect(() =>
      normaliseLocatorData({
        strategy: 'role',
        role: 'button',
        frame: { path: ['a', 'b', 'c', 'd', 'e', 'f'] },
      }),
    ).toThrow(/five nested frames/);
  });

  it('drops an empty frame chain rather than storing a hollow object', () => {
    expect(
      normaliseLocatorData({ strategy: 'role', role: 'button', frame: { path: [] } })
        .frame,
    ).toBeNull();
  });

  it('round-trips: normalised data renders to valid code', () => {
    const data = normaliseLocatorData({
      strategy: 'scopedRole',
      parent: { strategy: 'role', role: 'region', name: 'Profile', exact: true },
      child: { strategy: 'role', role: 'button', name: 'Save', exact: true },
    });
    expect(renderExpression(data)).toContain("getByRole('region'");
    expect(renderExpression(data)).toContain("getByRole('button'");
  });
});
