/**
 * Locator exports (FR-UIS-018).
 *
 * Three shapes, all generated from the scan result the user is looking at:
 * JSON for tooling, a TypeScript module and a Python module for pasting into a
 * test suite. Only elements with a recommended locator are exported — an
 * unresolved element has nothing to offer a test.
 */
import type { ScannedElement, UiScan } from '../../services/api/types';

export interface ExportRow {
  key: string;
  name: string;
  role: string;
  strategy: string;
  expression: string;
  pythonExpression: string;
  confidence: number;
  matchCount: number;
  status: string;
  frame: string;
}

function identifier(text: string, fallback: string): string {
  const cleaned = (text || '')
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();
  const safe = cleaned || fallback;
  return /^[0-9]/.test(safe) ? `_${safe}` : safe;
}

export function elementDisplayName(element: ScannedElement): string {
  const context = (element.context ?? {}) as Record<string, unknown>;
  const attributes = (element.attributes ?? {}) as Record<string, unknown>;
  return (
    element.accessibleName ||
    String(context.associatedLabel || '') ||
    String(attributes.placeholder || '') ||
    element.visibleText.slice(0, 60) ||
    String(attributes.name || '') ||
    element.elementKey
  );
}

export function toExportRows(elements: ScannedElement[]): ExportRow[] {
  return elements
    .map((element): ExportRow | null => {
      const best = (element.candidates ?? []).find(
        (c) => c.id === element.recommendedLocatorId,
      );
      if (!best) return null;
      return {
        key: element.elementKey,
        name: elementDisplayName(element),
        role: element.role,
        strategy: best.strategy,
        expression: best.expression,
        pythonExpression: best.pythonExpression,
        confidence: best.confidence,
        matchCount: best.matchCount,
        status: element.status,
        frame: element.frame?.title || element.frame?.name || 'main document',
      };
    })
    .filter((row): row is ExportRow => row !== null);
}

export function toJson(scan: UiScan, elements: ScannedElement[]): string {
  return JSON.stringify(
    {
      scanId: scan.id,
      url: scan.finalUrl || scan.url,
      pageTitle: scan.pageTitle,
      browser: scan.browser,
      scannedAt: scan.completedAt ?? scan.createdAt,
      metrics: scan.metrics,
      locators: toExportRows(elements),
    },
    null,
    2,
  );
}

export function toTypeScript(scan: UiScan, elements: ScannedElement[]): string {
  const rows = toExportRows(elements);
  const seen = new Set<string>();
  const lines = rows.map((row, index) => {
    let name = identifier(row.name, `element_${index + 1}`);
    while (seen.has(name)) name = `${name}_${index + 1}`;
    seen.add(name);
    return (
      `  /** ${row.role || row.strategy} · confidence ${row.confidence.toFixed(2)} */\n` +
      `  ${name}: (page: Page) => ${row.expression.replace(/^page/, 'page')},`
    );
  });
  return (
    `// Locators exported from UI scan ${scan.id}\n` +
    `// Page: ${scan.finalUrl || scan.url}\n` +
    `import type { Page } from '@playwright/test';\n\n` +
    `export const locators = {\n${lines.join('\n')}\n};\n`
  );
}

export function toPython(scan: UiScan, elements: ScannedElement[]): string {
  const rows = toExportRows(elements);
  const seen = new Set<string>();
  const lines = rows.map((row, index) => {
    let name = identifier(row.name, `element_${index + 1}`);
    while (seen.has(name)) name = `${name}_${index + 1}`;
    seen.add(name);
    return (
      `    # ${row.role || row.strategy} · confidence ${row.confidence.toFixed(2)}\n` +
      `    def ${name}(self):\n` +
      `        return ${row.pythonExpression.replace(/^page/, 'self.page')}\n`
    );
  });
  return (
    `"""Locators exported from UI scan ${scan.id}.\n\n` +
    `Page: ${scan.finalUrl || scan.url}\n` +
    `Generated by the UI Scanner; every locator was validated against the live page.\n"""\n\n` +
    `from playwright.sync_api import Page\n\n\n` +
    `class ScannedLocators:\n` +
    `    def __init__(self, page: Page) -> None:\n` +
    `        self.page = page\n\n` +
    (lines.join('\n') || '    pass\n')
  );
}

/** Human-readable scan report for the dissertation evidence trail (§29). */
export function toReport(scan: UiScan, elements: ScannedElement[]): string {
  const rows = toExportRows(elements);
  const metrics = (scan.metrics ?? {}) as Record<string, unknown>;
  const pct = (v: unknown): string =>
    typeof v === 'number' ? `${Math.round(v * 100)}%` : 'n/a';
  return [
    `UI Scan report`,
    `==============`,
    ``,
    `Scan id:          ${scan.id}`,
    `URL:              ${scan.finalUrl || scan.url}`,
    `Page title:       ${scan.pageTitle}`,
    `Browser:          ${scan.browser} (${scan.headless ? 'headless' : 'headed'})`,
    `Status:           ${scan.status}`,
    `Started:          ${scan.startedAt ?? '-'}`,
    `Completed:        ${scan.completedAt ?? '-'}`,
    `Duration:         ${scan.durationMs != null ? `${(scan.durationMs / 1000).toFixed(1)}s` : '-'}`,
    `Model:            ${scan.selectedModel || '(deterministic only)'}`,
    ``,
    `Scanned elements: ${scan.totalElements}`,
    `Unique locators:  ${scan.validLocatorCount}`,
    `Needs review:     ${scan.unresolvedCount}`,
    `Frames scanned:   ${scan.frameCount}`,
    `Warnings:         ${scan.warningCount}`,
    `Semantic rate:    ${pct(metrics.semanticLocatorRate)}`,
    `Test-id rate:     ${pct(metrics.testIdLocatorRate)}`,
    `CSS fallback:     ${pct(metrics.cssFallbackRate)}`,
    `XPath fallback:   ${pct(metrics.xpathFallbackRate)}`,
    `LLM fallback:     ${pct(metrics.llmFallbackRate)}`,
    `Avg. confidence:  ${typeof metrics.averageConfidence === 'number' ? metrics.averageConfidence.toFixed(2) : 'n/a'}`,
    ``,
    `Locators`,
    `--------`,
    ...rows.map(
      (r) =>
        `[${r.status}] ${r.name} (${r.role || r.strategy}, ${r.frame})\n` +
        `    ${r.expression}\n` +
        `    confidence ${r.confidence.toFixed(2)} · ${r.matchCount} match(es)`,
    ),
    ``,
    ...(scan.warnings?.length ? ['Warnings', '--------', ...scan.warnings] : []),
  ].join('\n');
}

/** Trigger a browser download of generated text. */
export function downloadText(filename: string, content: string, type: string): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
